### ISSUE TITLE
Unable to build with 5.0.0

### ISSUE THREAD

**Issue by tja4472** [timdeschryver/ngrx-etc#16]
Getting the following error building with the latest version 5.0.0.

```sh
> Executing task: npm run build <

> ng-task@0.0.0 build C:\VSCode\2020\git-hub-tim\ngrx-task
> ng build

ERROR in src/app/root-store/user-store/reducer.ts:9:27 - error TS7016: Could not find a declaration file for module 'ngrx-etc'. 'C:/VSCode/2020/git-hub-tim/ngrx-task/node_modules/ngrx-etc/ngrx-etc.js' implicitly has an 'any' type.
  Try `npm install @types/ngrx-etc` if it exists or add a new declaration (.d.ts) file containing `declare module 'ngrx-etc';`      

9 import { mutableOn } from 'ngrx-etc';
```

**Comment by timdeschryver** [comment]
Sorry for the inconvenience.
Never release on a friday 😅

I'll take a look at it tomorrow, thanks for report it.

**Comment by timdeschryver** [comment]
Hi, this should be resolved in v5.0.1.

If that's not the case feel free to re-open the issue.

**Comment by tja4472** [comment]
All good. Thank you.
